# DO NOT EDIT THIS FILE -- HWasly auto-generated file
{% if helpers.exists('HWasly.monit.general.enabled') and HWasly.monit.general.enabled|default("0") == "1" %}
monit_setup="/usr/local/hwasly/scripts/HWasly/Monit/setup.sh"
monit_enable="YES"
{% else %}
monit_enable="NO"
{% endif %}
